"""Minimal local stub for the untyped ``sqlcipher3`` driver (pysqlite fork).

Covers only the surface Healthspan uses; extend as call sites grow.
"""

from collections.abc import Iterable, Sequence
from typing import Any

class Error(Exception): ...
class DatabaseError(Error): ...
class OperationalError(DatabaseError): ...
class IntegrityError(DatabaseError): ...

class Cursor:
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def close(self) -> None: ...

class Connection:
    def execute(
        self, sql: str, parameters: Sequence[Any] | dict[str, Any] = ...
    ) -> Cursor: ...
    def executescript(self, sql_script: str) -> Cursor: ...
    def executemany(
        self, sql: str, seq_of_parameters: Iterable[Sequence[Any]]
    ) -> Cursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def backup(
        self,
        target: Connection,
        *,
        pages: int = ...,
        name: str = ...,
        sleep: float = ...,
    ) -> None: ...

def connect(
    database: str,
    timeout: float = ...,
    detect_types: int = ...,
    isolation_level: str | None = ...,
    check_same_thread: bool = ...,
    cached_statements: int = ...,
    uri: bool = ...,
) -> Connection: ...

version: str
sqlite_version: str
