"""SQLCipher connection factory and database provisioning (ADR-0028/0035/0037).

The single place that opens database connections: raw-key handoff (the
sanctioned ``PRAGMA key`` interpolation), the recorded pragma set, and
explicit transaction semantics (``isolation_level=None`` — the driver
never issues an implicit BEGIN/COMMIT, per ADR-0035). ``healthspan init``
provisions new files here so the persistent pragmas (WAL, application_id)
are set exactly once.
"""

import re
from pathlib import Path

import sqlcipher3

from healthspan.fsperm import set_owner_only
from healthspan.kdf import DbKey

# Persistent file header mark: self-identifies a Healthspan database
# (ADR-0035; independent of the schema_version table).
APPLICATION_ID = 0x48535041  # "HSPA"

_HEX64 = re.compile(r"^[0-9a-f]{64}$")


class DatabaseError(Exception):
    """A database could not be opened, keyed, or provisioned."""


def key_pragma(verb: str, key: DbKey) -> str:
    """The raw-key PRAGMA statement (ADR-0028's sanctioned interpolation).

    Only the ``.hex()`` of locally generated bytes is interpolated, and it
    is format-validated first — no user-supplied data can reach this.
    """
    hex_key = key.hex()
    if not _HEX64.fullmatch(hex_key):
        raise DatabaseError("derived key is not 64 lowercase hex characters")
    return f"""PRAGMA {verb} = "x'{hex_key}'";"""


def connect(database_path: Path, key: DbKey) -> sqlcipher3.Connection:
    """Open an existing encrypted database with the runtime pragma set.

    Raises :class:`DatabaseError` if the file is missing or the key does
    not open it (SQLCipher reports a wrong key as "file is not a
    database" on first read).
    """
    if not database_path.is_file():
        raise DatabaseError(f"database {database_path} does not exist")
    conn = _open(database_path, key)
    try:
        conn.execute("SELECT count(*) FROM sqlite_master").fetchone()
    except sqlcipher3.DatabaseError as exc:
        conn.close()
        raise DatabaseError(
            f"could not unlock {database_path}: wrong passphrase/secret key, "
            f"or the file is not a Healthspan database ({exc})"
        ) from exc
    _apply_runtime_pragmas(conn)
    return conn


def provision(database_path: Path, key: DbKey) -> None:
    """Create a new, empty, encrypted database file (``healthspan init``).

    Keys the file, sets the persistent pragmas (WAL journal mode,
    application_id), and applies owner-only permissions. The schema
    arrives separately via ``healthspan db migrate``.
    """
    if database_path.exists():
        raise DatabaseError(f"refusing to overwrite existing {database_path}")
    database_path.parent.mkdir(parents=True, exist_ok=True)
    conn = _open(database_path, key)
    try:
        _apply_runtime_pragmas(conn)
        conn.execute("PRAGMA journal_mode = WAL")
        conn.execute(f"PRAGMA application_id = {APPLICATION_ID}")
        # Force the header (and hence the file) to be written out.
        conn.execute("SELECT count(*) FROM sqlite_master").fetchone()
    finally:
        conn.close()
    set_owner_only(database_path)


def open_backup_target(target_path: Path, key: DbKey) -> sqlcipher3.Connection:
    """Open a keyed connection for the native backup API's target file.

    Lives here so this module remains the single place connections are
    opened (ADR-0035/0037). The target receives pages wholesale from
    ``Connection.backup``; the runtime pragma set still applies so any SQL
    a future caller runs through this handle meets the same discipline.
    """
    conn = _open(target_path, key)
    _apply_runtime_pragmas(conn)
    return conn


def rekey(conn: sqlcipher3.Connection, new_key: DbKey) -> None:
    """Re-encrypt every page under a new key (ADR-0028 rotation step 3)."""
    conn.execute(key_pragma("rekey", new_key))


def close(conn: sqlcipher3.Connection) -> None:
    """Close a factory connection, running ``PRAGMA optimize`` first."""
    try:
        conn.execute("PRAGMA optimize")
    finally:
        conn.close()


def integrity_ok(conn: sqlcipher3.Connection) -> bool:
    """Full ``PRAGMA integrity_check`` (ADR-0038 verification clause)."""
    rows = conn.execute("PRAGMA integrity_check").fetchall()
    return rows == [("ok",)]


def schema_version(conn: sqlcipher3.Connection) -> int | None:
    """Latest applied migration number, or None before the runner exists."""
    row = conn.execute(
        "SELECT count(*) FROM sqlite_master WHERE type='table' "
        "AND name='schema_version'"
    ).fetchone()
    if row is None or row[0] == 0:
        return None
    latest = conn.execute("SELECT max(version) FROM schema_version").fetchone()
    return None if latest is None else latest[0]


def _open(database_path: Path, key: DbKey) -> sqlcipher3.Connection:
    conn = sqlcipher3.connect(
        str(database_path),
        isolation_level=None,  # explicit transactions only (ADR-0035)
        check_same_thread=True,  # thread-affinity enforcement (ADR-0037)
    )
    conn.execute(key_pragma("key", key))
    return conn


def _apply_runtime_pragmas(conn: sqlcipher3.Connection) -> None:
    # The recorded per-connection set (ADR-0035 pragma table + ADR-0037).
    conn.execute("PRAGMA foreign_keys = ON")
    conn.execute("PRAGMA synchronous = NORMAL")
    conn.execute("PRAGMA busy_timeout = 5000")
